Nmkc/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('', include('myShop.urls')),
                  path('admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.site.site_header = 'NamasteStores'

myShop/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
    path('', index, name="index"),
    path('store/<slug>', store, name="store"),
    path('item_details/<slug>', item_details, name="item_details"),
    path('contact', contact, name="contact"),
    path('login', login_user, name="login"),
    path('register', register, name="register"),
    path('users/', users, name="users"),
    path('logout/', logout_user, name="logout"),
    path('password_reset', auth_views.PasswordResetView.as_view(template_name='pages/password_reset.html'),
         name='password_reset'),
    path('password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='pages/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password_reset_done',
         auth_views.PasswordResetDoneView.as_view(template_name='pages/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset_complete',
         auth_views.PasswordResetCompleteView.as_view(template_name='pages/password_reset_complete.html'),
         name='password_reset_complete'),
    path('search_results', search_results, name='search_results'),
]

myShop/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor.fields import RichTextField
from django.utils import timezone


# Create your models here.
class Menu(models.Model):
    menu_name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=120, unique=True)
    status = models.BooleanField(default=0)

    def __str__(self):
        return self.menu_name

    class Meta:
        verbose_name_plural = 'Menu'


class SubMenu(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=120, unique=True)
    status = models.BooleanField(default=0)
    posted_by = models.ForeignKey(User, on_delete=models.CASCADE)
    posted_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Sub Menu'


class Items(models.Model):
    sub_menu = models.ForeignKey(SubMenu, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=120, unique=True)
    status = models.BooleanField(default=0)
    image = models.ImageField(blank=True, upload_to='menus')
    description = RichTextField()
    price = models.IntegerField()
    posted_by = models.ForeignKey(User, on_delete=models.CASCADE)
    posted_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.item_name

    class Meta:
        verbose_name_plural = 'Items'


class Slider(models.Model):
    title = models.CharField(max_length=100)
    slug = models.CharField(max_length=120, unique=True)
    description = RichTextField()
    image = models.ImageField(blank=False, upload_to='Slider')
    status = models.BooleanField(default=0)

    def __str__(self):
        return self.title

myShop/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.db.models import Q

from .models import *


# Create your views here.
def index(request):
    content = {
        'title': 'Home',
        'sliderData': Slider.objects.all().order_by('-id')
    }
    return render(request, 'pages/home.html', content)


def store(request, slug):
    content = {
        'title': 'Store',
        'submenuData': SubMenu.objects.prefetch_related('items_set').filter(slug=slug)
    }
    return render(request, 'pages/store.html', content)


def item_details(request, slug):
    content = {
        'title': 'Item-details',
        'itemData': Items.objects.filter(slug=slug)
    }
    return render(request, 'pages/item_details.html', content)


def contact(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        message = request.POST['message']
        send_mail('Hi this is ' + name, message, email, ['nmkcktm@gmail.com'])
        messages.success(request, "Message sent successfully")
        return redirect('contact')
    else:
        content = {
            'title': 'Contact'
        }
        return render(request, 'pages/contact.html', content)


def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('users')
        else:
            messages.error(request, 'Error loging in')
            return redirect('login')
    else:
        content = {
            'title': 'Login',
            'form': AuthenticationForm
        }
    return render(request, 'pages/login.html', content)


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'User registered successfully')
            return redirect('register')
        else:
            messages.error(request, 'User not registered')
            return redirect('register')
    else:
        content = {
            'title': 'Register',
            'form': UserCreationForm
        }
    return render(request, 'pages/register.html', content)


def logout_user(request):
    if request.method == 'POST':
        logout(request)
        return redirect('login')


@login_required(login_url='login')
def users(request):
    content = {
        'title': 'User'
    }
    return render(request, 'pages/Users.html', content)


def search_results(request):
    if request.method == 'POST':
        search = request.POST['search']
        item_list = Items.objects.filter(Q(item_name__icontains=search) or Q(sub_menu__icontains=search))
    content = {
        'title': 'Search-results',
        'items_list': item_list
    }
    return render(request, 'pages/search_results.html', content)

myShop/templates/layouts/footer.html
{% load static %}
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="address col-6"><h3>Visit Our Store</h3>
                <img src="{% static 'frontend/icons/addressicon.png' %}" alt="" class="infoicon"><br>
                Keltole, Masangalli<br>Kathmandu, Nepal
            </div>
            <div class="openhrs col-6"><h3>Opening Hours</h3>
                <img src="{% static 'frontend/icons/openhrsicon.png' %}" alt="" class="infoicon"><br>
                Sunday-Friday<br>9am-7pm
            </div>
        </div>
        Copyright &copy; 2019 Namaste Multi-Kitchen Concern
    </div>
</div>
<script type="text/javascript" src="js/jquery-3.4.1.min.js"></script>
<script type="text/javascript" src="{% static 'frontend/js/animate.js' %}"></script>
<script type="text/javascript" src="{% static 'frontend/js/function.js' %}"></script>
<script type="text/javascript" src="{% static 'frontend/js/slick.js' %}"></script>
<script type="text/javascript" src="{% static 'frontend/js/slick-min.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function(){
        $('.slick_slider').slick({
            arrows:false,
            autoplay:true,
            autoplaySpeed:1000
        });
    });

</script>
</body>
</html>

myShop/templates/layouts/header.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% if title %}
        NMKC :: {{title}}
        {% else %}
        NMKC :: WELCOME
        {% endif %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'frontend/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'frontend/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'frontend/css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'frontend/css/slick-theme.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Orbitron:400,500,700,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Strait&display=swap" rel="stylesheet">
    <link rel="icon" href="{% static 'frontend/logo/logo.png' %}">

</head>
<body>
<div class="header sticky-top">
    <div class="container">
        <div class="row">
            <div class="col-6">

                <div class="navbar-brand fadeInUp animatable">
                    <img src="{% static 'frontend/logo/logo.png' %}" alt="">
                    NAMASTE

                </div>


            </div>
            <div class="col-6 fadeInUp animatable">
                <form class="form-inline" action="{% url 'search_results' %}" method="post">
                    {% csrf_token %}
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"
                           name="search" required>
                    <button class="btn btn-success my-2 my-sm-0" style="height:30px; line-height:0.5" type="submit">
                        Search
                    </button>
                </form>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="navigationBar text-right menu-1 fadeInUp animatable">
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'index' %}">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">Store</a>
                        <div class="dropdown-menu">
                            {% for menu in menuData %}
                            {% if menu.submenu_set.all %}
                            <div class="dropdown-submenu dropdown">
                                <a class="dropdown-item dropdown-toggle">{{menu.menu_name}}</a>
                                <div class="dropdown-menu">
                                    {% for submenu in menu.submenu_set.all %}
                                    <a class="dropdown-item" href="{% url 'store' submenu.slug %}">{{submenu.title}}</a>
                                    {% endfor %}
                                </div>
                            </div>
                            {% else %}
                            <a class="dropdown-item" href="#">{{menu.menu_name}}</a>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <form action="{% url 'logout' %}" method="post">
                            {% csrf_token %}
                            <button class="nav-link" style="background:transparent; color:white;">Logout</button>
                        </form>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                        {% endif %}
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

myShop/templates/master/master.html
{% include 'layouts/header.html' %}

{% block content %}

{% endblock %}

{% include 'layouts/footer.html' %}

myShop/templates/pages/contact.html
{% extends 'master/master.html' %}
{% load static %}

{% block content %}
<div class="contact">
    <div class="container">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success">{{message}}</div>
        {% endfor %}
        {% endif %}
        <div class="row">

            <form action="{% url 'contact' %}" method="post" class="col-6 form-group">
                {% csrf_token %}
                <h2>Any queries?</h2>
                <input type="text" class="form-control" name="name" placeholder="Enter your name here" required><br>
                <input type="email" class="form-control" name="email" placeholder="Enter your email here" required><br>
                <textarea class="form-control rounded-0" id="Textarea" rows="7" name="message"
                          placeholder="Enter your message here" required></textarea>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            <div class="col-6 links">
                <a href="https://www.facebook.com/pratistha.kansakar"><img src="{% static 'frontend/icons/fbicon.png' %}" alt=""
                                                                           class="contacticon"></a><br>
                <a href="https://www.instagram.com/namasteconcern/"><img src="{% static 'frontend/icons/igicon.png' %}" alt=""
                                                                         class="contacticon"></a><br>
                <a href="https://twitter.com/KitchenMulti"><img src="{% static 'frontend/icons/twittericon.png' %}" alt=""
                                                                         class="contacticon"></a><br>
                <a href="tel:01-4223669"><img src="{% static 'frontend/icons/callicon.png' %}" alt="" class="contacticon"></a>4223669 /
                4223718<br>
            </div>
        </div>

    </div>

</div>

{% endblock %}

myShop/templates/pages/home.html
{% extends 'master/master.html' %}
{% load static %}

{% block content %}

<div class="slider">
    <div class="container">
        <div class="row slick_slider">
            {% for slide in sliderData %}
            <div class="slides"><img src="{{slide.image.url}}" alt=""><h4>{{slide.title}}</h4><h6>{{slide.description|safe|slice:'50'}}</h6></div>
            {% endfor %}
        </div>
    </div>
</div>
<div id="aboutus">
    <div class="container ">
        <div class="row row-1 justify-content-center fadeInUp  animatable">
            <div class="col-6">
                <h2 class="title">WELCOME TO NAMASTE</h2>

            </div>

        </div>
        <div class=" row row-2 fadeInUp  animatable">
            <div class="col-4">
                <img src="{% static 'frontend/icons/opened.png' %}" class="icon" alt="">
                <h3>We have been providing service to you since 1997A.D</h3>
            </div>
            <div class="col-4">
                <img src="{% static 'frontend/icons/qualityproduct.png' %}" class="icon" alt="">
                <h3>We provide you high quality products at the best price</h3>
            </div>
            <div class="col-4">
                <img src="{% static 'frontend/icons/service.png' %}" class="icon" alt="">
                <h3>We provide great service to meet customer satisfaction</h3>
            </div>
        </div>
    </div>

</div>

{% endblock %}

myShop/templates/pages/item_details.html
{% extends 'master/master.html' %}
{% load static %}

{% block content %}
<div class="item_details">
    <div class="container">
        {% for items in itemData %}
        <div class="detail_row">
            <img src="{{items.image.url}}" class="detail_img" alt="itempicture"><br><br>
            <h4 class="item_title">{{items.item_name}}</h4>
            <p class="item_description">{{items.description|safe}}</p>
            <p>Price : Rs{{items.price}} </p>
        </div>

        {% endfor %}
    </div>

</div>

</div>

{% endblock %}

myShop/templates/pages/login.html
{% extends 'master/master.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="loginform">
    <div class="container">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger">{{message}}</div>
        {% endfor %}
        {% endif %}
        <form action="{% url 'login' %}" method="post">
            {% csrf_token %}
            {{form| crispy}}
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
        <a href="{% url 'password_reset' %}">Password Reset</a>
    </div>
</div>
{% endblock %}

myShop/templates/pages/password_reset.html
{% extends 'master/master.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="loginform">
    <div class="container">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger">{{message}}</div>
        {% endfor %}
        {% endif %}
        <form action="" method="post">
            {% csrf_token %}
            {{form| crispy}}
            <button type="submit" class="btn btn-primary">Send</button>
        </form>
    </div>
</div>
{% endblock %}

myShop/templates/pages/password_reset_complete.html
{% extends 'master/master.html' %}

{% block content %}
<div class="loginform">
    <div class="container">
        <h2 style="font-family: 'Strait', sans-serif;">Password has been changed successfully.<br>Login to continue.</h2>
    </div>
</div>
{% endblock %}

myShop/templates/pages/password_reset_confirm.html
{% extends 'master/master.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="loginform">
    <div class="container">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger">{{message}}</div>
        {% endfor %}
        {% endif %}
        <form action="" method="post">
            {% csrf_token %}
            {{form| crispy}}
            <button type="submit" class="btn btn-primary">Send</button>
        </form>
    </div>
</div>
{% endblock %}

myShop/templates/pages/password_reset_done.html
{% extends 'master/master.html' %}

{% block content %}
<div class="loginform">
    <div class="container">
        <h2 style="font-family: 'Strait', sans-serif;">Check your email and click on the link to set your new password.</h2>
    </div>
</div>
{% endblock %}

myShop/templates/pages/register.html
{% extends 'master/master.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="loginform">
    <div class="container">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info">{{message}}</div>
        {% endfor %}
        {% endif %}
        <form action="" method="post">
            {% csrf_token %}
            {{form| crispy}}
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
</div>

{% endblock %}

myShop/templates/pages/search_results.html
{% extends 'master/master.html' %}
{% load static %}

{% block content %}
<div class="items">
    <div class="container">
        <div class="row">
            {% if items_list %}
            {% for item in items_list %}
            <div class="col-4">
                {% if item.image%}
                <img src="{{item.image.url}}" class="img-fluid" alt="itempicture"><br>
                {% endif %}
                <a href="{% url 'item_details' item.slug %}">{{item.item_name}}</a>
            </div>
            {% endfor %}
            {% else %}
            <div style="margin:auto; white-space:pre-wrap;">
                <h4 style="font-family:'Strait';">Sorry no items matched.</h4>
            </div>
            {% endif %}

        </div>


    </div>

</div>

{% endblock %}

myShop/templates/pages/store.html
{% extends 'master/master.html' %}
{% load static %}

{% block content %}
<div class="items">
    <div class="container">
        <div class="row">
            {% for submenu in submenuData %}
            {% if submenu.items_set.all %}
            {% for items in submenu.items_set.all %}
            <div class="col-4">
                {% if items.image%}
                <img src="{{items.image.url}}" class="img-fluid" alt="itempicture"><br>
                {% endif %}
                <a href="{% url 'item_details' items.slug %}">{{items.item_name}}</a>
            </div>
            {% endfor %}
            {% endif %}
            {% endfor %}
        </div>


    </div>

</div>

{% endblock %}

myShop/templates/pages/users.html
{% extends 'master/master.html' %}
{% block content %}
<div class="container">
    <h1 style="text-align:center; padding:8%;">Welcome {{user.get_username|title}}</h1>
</div>

{% endblock %}